export interface CatalogProduct {
  id: string;
  name: string;
  unit: string;
  tagline: string;
  description: string;
  keywords: string[];
  categories: string[];
  status: "Live" | "Beta";
  href: string;
  type: "product" | "service" | "template" | "course";
  price?: string;
}

const CATALOG: CatalogProduct[] = [
  // ── BrainSAIT Health ──
  { id: "claimlinc", name: "ClaimLinc", unit: "health", tagline: "AI Revenue Cycle Management", description: "End-to-end RCM automation — eligibility, claims submission, denial management, and payment reconciliation via NPHIES Direct Gateway.", keywords: ["claims", "revenue cycle", "rcm", "billing", "nphies", "insurance", "denial", "eligibility", "reimbursement", "coding"], categories: ["revenue-cycle", "nphies", "claims"], status: "Live", href: "/products/health/claimlinc", type: "product" },
  { id: "clinicallinc", name: "ClinicalLinc", unit: "health", tagline: "Clinical Decision Intelligence", description: "AI-powered clinical decision support with Arabic-capable NLP, drug interaction checks, and evidence-based recommendations.", keywords: ["clinical", "decision support", "cdss", "nlp", "drug interaction", "evidence", "arabic"], categories: ["clinical-ai", "ai", "decision-support"], status: "Live", href: "/products/health/clinicallinc", type: "product" },
  { id: "codinglinc", name: "CodingLinc", unit: "health", tagline: "ICD-10-AM & CPT Coding Assistant", description: "Automated medical coding with AI — ICD-10-AM, CPT, and Saudi procedure codes with real-time validation.", keywords: ["coding", "icd-10", "cpt", "medical coding", "procedure codes", "automation", "saudi"], categories: ["coding", "revenue-cycle", "claims"], status: "Live", href: "/products/health/codinglinc", type: "product" },
  { id: "drg-suite", name: "BrainSAIT DRG Suite", unit: "health", tagline: "Bilingual Saudi DRG Automation", description: "APR-DRG / EAPG grouper with bilingual Arabic/English code-switching NLP, CDI nudges, and NPHIES claims submission. Ready for Saudi reimbursement workflows.", keywords: ["drg", "apr-drg", "eapg", "coding", "nphies", "saudi", "arabic", "bilingual", "cdi", "claims", "revenue cycle"], categories: ["drg", "coding", "revenue-cycle", "nphies", "claims"], status: "Live", href: "/marketplace/drg", type: "product", price: "SAR 4,500 / bed / month" },
  { id: "priorauthlinc", name: "PriorAuthLinc", unit: "health", tagline: "Automated Prior Authorization", description: "Intelligent prior authorization with NPHIES integration — auto-checks medical necessity, policy rules, and eligibility.", keywords: ["prior authorization", "prior auth", "pre-auth", "nphies", "eligibility", "insurance", "approval"], categories: ["revenue-cycle", "nphies", "claims"], status: "Live", href: "/products/health/priorauthlinc", type: "product" },
  { id: "compliancelinc", name: "ComplianceLinc", unit: "health", tagline: "NPHIES & Regulatory Compliance", description: "Automated compliance monitoring across PDPL, CBAHI, NCA-ECC, MOH, and NPHIES standards.", keywords: ["compliance", "nphies", "pdpl", "cbahi", "nca-ecc", "moh", "regulation", "audit"], categories: ["compliance", "regulatory", "governance"], status: "Live", href: "/products/health/compliancelinc", type: "product" },
  { id: "radiolinc", name: "RadioLinc", unit: "health", tagline: "Radiology AI Workflow", description: "AI-assisted radiology workflow — image analysis, automated reporting, and PACS integration.", keywords: ["radiology", "imaging", "pacs", "x-ray", "mri", "ct", "reporting", "ai", "diagnostic"], categories: ["clinical-ai", "imaging", "diagnostics"], status: "Live", href: "/products/health/radiolinc", type: "product" },
  { id: "lablinc", name: "LabLinc", unit: "health", tagline: "Laboratory Workflow Automation", description: "End-to-end lab workflow from order entry to result delivery with AI-driven quality checks.", keywords: ["lab", "laboratory", "lis", "pathology", "test", "results", "automation"], categories: ["lab", "operations"], status: "Beta", href: "/products/health/lablinc", type: "product" },
  { id: "pharmacylinc", name: "PharmacyLinc", unit: "health", tagline: "Medication Management", description: "AI-powered pharmacy management — drug interaction checks, inventory, dispensing, and patient counseling.", keywords: ["pharmacy", "medication", "drug", "inventory", "dispensing", "interaction"], categories: ["pharmacy", "operations"], status: "Beta", href: "/products/health/pharmacylinc", type: "product" },
  { id: "appointmentlinc", name: "AppointmentLinc", unit: "health", tagline: "Scheduling Platform", description: "Smart patient scheduling with AI-optimised slot allocation, automated reminders, and multi-channel booking.", keywords: ["scheduling", "appointment", "booking", "calendar", "reminders", "patient"], categories: ["patient-engagement", "operations"], status: "Live", href: "/products/health/appointmentlinc", type: "product" },
  { id: "patientlinc", name: "PatientLinc", unit: "health", tagline: "Patient Engagement Portal", description: "Omnichannel patient portal — appointments, lab results, billing, telemedicine, and health records.", keywords: ["patient portal", "patient engagement", "telemedicine", "health records", "ehr", "billing", "portal"], categories: ["patient-engagement", "digital-health"], status: "Live", href: "/products/health/patientlinc", type: "product" },
  { id: "referrallinc", name: "ReferralLinc", unit: "health", tagline: "Smart Referral Management", description: "Digital referral network connecting primary care to specialists with automated prior auth and status tracking.", keywords: ["referral", "specialist", "primary care", "referral network", "prior auth"], categories: ["operations", "network"], status: "Beta", href: "/products/health/referrallinc", type: "product" },
  { id: "basma", name: "Basma Health", unit: "health", tagline: "AI Receptionist & Voice Secretary", description: "Voice AI receptionist handling appointments, inquiries, and triage in Arabic and English — 24/7.", keywords: ["voice", "receptionist", "ai assistant", "arabic", "appointment", "triage", "secretary"], categories: ["patient-engagement", "ai", "voice"], status: "Live", href: "/products/health/basma", type: "product" },

  // ── BrainSAIT AI ──
  { id: "masterlinc", name: "MasterLINC", unit: "ai", tagline: "Enterprise AI Orchestrator", description: "Central AI agent orchestrator that routes tasks across specialised LINC agents — clinical, operational, administrative — with full audit trail.", keywords: ["orchestrator", "ai agents", "orchestration", "task routing", "llm", "agent"], categories: ["ai", "agents", "orchestration"], status: "Live", href: "/products/ai/masterlinc", type: "product" },
  { id: "agent-studio", name: "Agent Studio", unit: "ai", tagline: "Custom AI Agent Builder", description: "No-code agent builder for healthcare. Design, train, and deploy custom AI agents with drag-and-drop simplicity.", keywords: ["agent builder", "no-code", "ai agent", "custom ai", "drag drop", "studio"], categories: ["ai", "agents", "developer"], status: "Beta", href: "/products/ai/agent-studio", type: "product" },
  { id: "agent-marketplace", name: "Agent Marketplace", unit: "ai", tagline: "Pre-built AI Agent Store", description: "Browse and deploy pre-built healthcare AI agents — radiology, coding, compliance, patient communication, and more.", keywords: ["agent store", "pre-built", "ai marketplace", "healthcare ai", "deploy"], categories: ["ai", "agents", "marketplace"], status: "Live", href: "/products/ai/agent-marketplace", type: "product" },
  { id: "agent-analytics", name: "Agent Analytics", unit: "ai", tagline: "AI Performance Dashboard", description: "Real-time analytics on agent performance, cost per task, accuracy rates, and ROI tracking across all deployed agents.", keywords: ["analytics", "ai monitoring", "performance", "roi", "dashboard", "metrics"], categories: ["ai", "analytics", "observability"], status: "Live", href: "/products/ai/agent-analytics", type: "product" },
  { id: "agent-monitor", name: "Agent Monitor", unit: "ai", tagline: "AI Agent Observability", description: "Production monitoring for AI agents — latency, error rates, hallucination detection, and human-in-the-loop oversight.", keywords: ["monitoring", "observability", "ai safety", "hallucination", "latency", "errors"], categories: ["ai", "observability", "safety"], status: "Beta", href: "/products/ai/agent-monitor", type: "product" },
  { id: "prompt-studio", name: "Prompt Studio", unit: "ai", tagline: "Healthcare Prompt Engineering", description: "Design, test, and version-control prompts optimised for medical use cases with built-in safety guardrails.", keywords: ["prompt", "prompt engineering", "llm", "safety", "medical", "version control"], categories: ["ai", "developer", "llm"], status: "Live", href: "/products/ai/prompt-studio", type: "product" },
  { id: "workflow-builder", name: "Workflow Builder", unit: "ai", tagline: "AI Workflow Automation", description: "Visual workflow builder connecting AI agents, APIs, and human tasks into automated healthcare processes.", keywords: ["workflow", "automation", "visual builder", "ai workflow", "process"], categories: ["ai", "automation", "operations"], status: "Beta", href: "/products/ai/workflow-builder", type: "product" },
  { id: "mcp-gateway", name: "MCP Gateway", unit: "ai", tagline: "Model Context Protocol Gateway", description: "Standardised interface for connecting AI agents to healthcare data sources via the MCP protocol — FHIR, HL7, EHRs.", keywords: ["mcp", "protocol", "gateway", "ai agents", "data sources", "fhir", "hl7"], categories: ["ai", "integration", "developer"], status: "Live", href: "/products/ai/mcp-gateway", type: "product" },

  // ── BrainSAIT Cloud ──
  { id: "healthhub", name: "HealthHub", unit: "cloud", tagline: "Unified Integration Platform", description: "Central healthcare integration hub connecting EHRs, labs, pharmacies, and government systems through a single pane of glass.", keywords: ["integration", "ehr", "interoperability", "hub", "connect", "health systems"], categories: ["integration", "interoperability", "cloud"], status: "Live", href: "/products/cloud/healthhub", type: "product" },
  { id: "oracle-bridge", name: "Oracle Bridge", unit: "cloud", tagline: "Oracle Health Integration", description: "Native bridge to Oracle Health (Cerner) — bi-directional FHIR/HL7 sync for clinical and administrative data.", keywords: ["oracle", "cerner", "bridge", "integration", "fhir", "hl7", "ehr"], categories: ["integration", "ehr", "cloud"], status: "Live", href: "/products/cloud/oracle-bridge", type: "product" },
  { id: "sap-bridge", name: "SAP Bridge", unit: "cloud", tagline: "SAP Healthcare Integration", description: "Connect SAP ERP and healthcare modules to BrainSAIT platform for unified financial and clinical workflows.", keywords: ["sap", "erp", "bridge", "integration", "financial", "enterprise"], categories: ["integration", "erp", "cloud"], status: "Beta", href: "/products/cloud/sap-bridge", type: "product" },
  { id: "dynamics-bridge", name: "Dynamics Bridge", unit: "cloud", tagline: "Microsoft Dynamics Integration", description: "Seamless integration with Microsoft Dynamics 365 for CRM, finance, and healthcare operations.", keywords: ["dynamics", "microsoft", "crm", "integration", "finance"], categories: ["integration", "crm", "cloud"], status: "Beta", href: "/products/cloud/dynamics-bridge", type: "product" },
  { id: "salesforce-bridge", name: "Salesforce Bridge", unit: "cloud", tagline: "Salesforce Health Cloud Sync", description: "Bi-directional sync between Salesforce Health Cloud and BrainSAIT for patient engagement and CRM.", keywords: ["salesforce", "health cloud", "crm", "sync", "integration", "patient"], categories: ["integration", "crm", "cloud"], status: "Beta", href: "/products/cloud/salesforce-bridge", type: "product" },
  { id: "nphies-gateway", name: "NPHIES Gateway", unit: "cloud", tagline: "National Health Insurance Gateway", description: "Direct integration with NPHIES for claims submission, eligibility, prior authorization, and real-time status.", keywords: ["nphies", "gateway", "claims", "eligibility", "prior auth", "insurance", "national"], categories: ["integration", "nphies", "gateway"], status: "Live", href: "/products/cloud/nphies-gateway", type: "product" },
  { id: "fhir-gateway", name: "FHIR Gateway", unit: "cloud", tagline: "FHIR R4 Interoperability Hub", description: "Enterprise FHIR R4 server with SMART-on-FHIR, bulk data export, and subscription-based event notifications.", keywords: ["fhir", "r4", "interoperability", "smart", "bulk data", "subscription", "api"], categories: ["integration", "fhir", "api"], status: "Live", href: "/products/cloud/fhir-gateway", type: "product" },
  { id: "hl7-gateway", name: "HL7 Gateway", unit: "cloud", tagline: "HL7 v2/v3 Message Engine", description: "Full HL7 v2.x and v3 message processing, transformation, routing, and validation engine.", keywords: ["hl7", "v2", "v3", "message", "transformation", "routing", "integration"], categories: ["integration", "hl7", "messaging"], status: "Live", href: "/products/cloud/hl7-gateway", type: "product" },
  { id: "api-gateway", name: "API Gateway", unit: "cloud", tagline: "Healthcare API Management", description: "Unified API gateway with rate limiting, authentication, monitoring, and developer portal for healthcare APIs.", keywords: ["api", "gateway", "rate limiting", "authentication", "developer portal", "management"], categories: ["api", "integration", "developer"], status: "Live", href: "/products/cloud/api-gateway", type: "product" },
  { id: "integration-marketplace", name: "Integration Marketplace", unit: "cloud", tagline: "Pre-built Connector Store", description: "Browse and deploy pre-built integrations and connectors for the most common healthcare and ERP systems.", keywords: ["connectors", "integration", "marketplace", "pre-built", "erp", "healthcare"], categories: ["integration", "marketplace", "cloud"], status: "Live", href: "/products/cloud/integration-marketplace", type: "product" },

  // ── BrainSAIT Trust ──
  { id: "trust-layer", name: "Trust Layer", unit: "trust", tagline: "Healthcare Trust Infrastructure", description: "Zero-trust security layer for healthcare — identity verification, access control, audit logging, and data encryption across all touchpoints.", keywords: ["trust", "security", "zero trust", "identity", "access control", "encryption", "audit"], categories: ["trust", "security", "compliance"], status: "Live", href: "/products/trust/trust-layer", type: "product" },
  { id: "kyb-api", name: "KYB API", unit: "trust", tagline: "Know Your Business Verification", description: "Automated business verification via Wathq integration — license validation, ownership structure, compliance status, and risk scoring.", keywords: ["kyb", "wathq", "verification", "business", "license", "compliance", "risk"], categories: ["trust", "verification", "compliance"], status: "Live", href: "/products/trust/kyb-api", type: "product" },
  { id: "ai-risk-score", name: "AI Risk Score", unit: "trust", tagline: "Vendor & Partner Risk Intelligence", description: "AI-driven risk scoring for healthcare vendors, contractors, and partners — financial, operational, and compliance risks.", keywords: ["risk", "vendor", "partner", "risk scoring", "financial", "operational", "ai"], categories: ["trust", "risk", "analytics"], status: "Live", href: "/products/trust/ai-risk-score", type: "product" },
  { id: "vendor-verification", name: "Vendor Verification", unit: "trust", tagline: "Healthcare Vendor Due Diligence", description: "End-to-end vendor verification — license checks, certification validation, performance history, and regulatory compliance.", keywords: ["vendor", "verification", "due diligence", "license", "certification", "procurement"], categories: ["trust", "verification", "procurement"], status: "Live", href: "/products/trust/vendor-verification", type: "product" },
  { id: "credential-verification", name: "Credential Verification", unit: "trust", tagline: "Healthcare Credentialing", description: "Automated credential verification for healthcare professionals — licenses, certifications, specialisations, and disciplinary history.", keywords: ["credentialing", "verification", "license", "certification", "healthcare professional", "doctor"], categories: ["trust", "verification", "workforce"], status: "Live", href: "/products/trust/credential-verification", type: "product" },
  { id: "provider-registry", name: "Provider Registry", unit: "trust", tagline: "Healthcare Provider Directory", description: "Centralised provider registry with verified credentials, specialties, locations, and real-time availability across Saudi Arabia.", keywords: ["provider", "registry", "directory", "credentials", "specialties", "saudi"], categories: ["trust", "network", "directory"], status: "Live", href: "/products/trust/provider-registry", type: "product" },
  { id: "digital-certificates", name: "Digital Certificates", unit: "trust", tagline: "Blockchain-Verified Credentials", description: "Issuance and verification of digital certificates for healthcare professionals using blockchain-anchored trust.", keywords: ["certificates", "blockchain", "digital", "verification", "credentials", "healthcare"], categories: ["trust", "verification", "blockchain"], status: "Beta", href: "/products/trust/digital-certificates", type: "product" },
  { id: "compliance-monitor", name: "Compliance Monitor", unit: "trust", tagline: "Regulatory Compliance Tracking", description: "Continuous monitoring across PDPL, NPHIES, CBAHI, NCA-ECC, MOH, ISO 27001, SAMA, and SFDA regulations.", keywords: ["compliance", "monitoring", "pdpl", "nphies", "cbahi", "nca", "moh", "iso", "sama", "sfda"], categories: ["compliance", "monitoring", "regulatory"], status: "Live", href: "/products/trust/compliance-monitor", type: "product" },
  { id: "audit-center", name: "Audit Center", unit: "trust", tagline: "Healthcare Audit Management", description: "Centralised audit trail for all platform activities — access logs, data changes, consent records, and compliance evidence.", keywords: ["audit", "audit trail", "logs", "compliance", "evidence", "access", "changes"], categories: ["compliance", "audit", "security"], status: "Live", href: "/products/trust/audit-center", type: "product" },
  { id: "pdpl-manager", name: "PDPL Manager", unit: "trust", tagline: "Personal Data Protection Toolkit", description: "End-to-end PDPL compliance toolkit — consent management, data mapping, breach notifications, and subject rights requests.", keywords: ["pdpl", "data protection", "privacy", "consent", "data mapping", "breach", "subject rights"], categories: ["compliance", "privacy", "regulatory"], status: "Live", href: "/products/trust/pdpl-manager", type: "product" },

  // ── BrainSAIT Academy ──
  { id: "academy", name: "Academy LMS", unit: "academy", tagline: "BrainSAIT Learning Platform", description: "Central healthcare education hub — accredited courses, professional development, and continuous medical education.", keywords: ["learning", "education", "courses", "cme", "training", "lms", "healthcare"], categories: ["education", "lms", "training"], status: "Live", href: "/products/academy/academy", type: "product" },
  { id: "lms", name: "LMS Platform", unit: "academy", tagline: "Healthcare Learning Management", description: "Enterprise LMS with Arabic support — course authoring, assessments, progress tracking, and certification management.", keywords: ["lms", "learning management", "courses", "arabic", "authoring", "certification"], categories: ["education", "lms", "training"], status: "Live", href: "/products/academy/lms", type: "product" },
  { id: "certification", name: "Certification Program", unit: "academy", tagline: "Healthcare Professional Certification", description: "Industry-recognised certifications in NPHIES, ICD-10-AM coding, healthcare AI, and compliance management.", keywords: ["certification", "nphies", "icd-10", "coding", "healthcare ai", "compliance", "professional"], categories: ["education", "certification", "training"], status: "Live", href: "/products/academy/certification", type: "product" },
  { id: "coding-academy", name: "Coding Academy", unit: "academy", tagline: "ICD-10-AM & CPT Bootcamp", description: "Intensive medical coding bootcamp with hands-on practice, real-world cases, and NPHIES-compliant coding certification.", keywords: ["coding", "bootcamp", "icd-10", "cpt", "medical coding", "training"], categories: ["education", "coding", "bootcamp"], status: "Live", href: "/products/academy/coding-academy", type: "course" },
  { id: "nphies-academy", name: "NPHIES Academy", unit: "academy", tagline: "NPHIES Certification Program", description: "Comprehensive NPHIES training — claims submission, eligibility, prior auth, and compliance for providers and payers.", keywords: ["nphies", "training", "certification", "claims", "eligibility", "prior auth"], categories: ["education", "nphies", "certification"], status: "Live", href: "/products/academy/nphies-academy", type: "course" },
  { id: "ai-academy", name: "AI Academy", unit: "academy", tagline: "Healthcare AI Training", description: "Practical AI training for healthcare professionals — clinical AI, prompt engineering, LLM safety, and deployment.", keywords: ["ai", "training", "llm", "prompt engineering", "healthcare ai", "safety"], categories: ["education", "ai", "training"], status: "Live", href: "/products/academy/ai-academy", type: "course" },
  { id: "developer-academy", name: "Developer Academy", unit: "academy", tagline: "Health-Tech Developer Training", description: "Technical training for healthcare developers — FHIR, HL7, SMART-on-FHIR, healthcare API development, and MCP protocol.", keywords: ["developer", "training", "fhir", "hl7", "api", "mcp", "technical"], categories: ["education", "developer", "training"], status: "Beta", href: "/products/academy/developer-academy", type: "course" },
  { id: "simulation-lab", name: "Simulation Lab", unit: "academy", tagline: "Virtual Healthcare Simulation", description: "AI-powered clinical simulation environment for training doctors, nurses, and administrators in realistic scenarios.", keywords: ["simulation", "training", "clinical", "virtual", "doctors", "nurses", "scenarios"], categories: ["education", "simulation", "training"], status: "Beta", href: "/products/academy/simulation-lab", type: "product" },

  // ── BrainSAIT Education — Premium Interactive E-Courses ──
  { id: "ecourse-coding-ksa", name: "Coding KSA", unit: "academy", tagline: "Programming for Saudi Healthcare", description: "Interactive bilingual (AR/EN) programming course — Python, healthcare APIs, FHIR integration, and AI-assisted coding with gamified challenges.", keywords: ["coding", "programming", "python", "fhir", "healthcare apis", "arabic", "bilingual", "bootcamp"], categories: ["education", "course", "programming", "arabic"], status: "Live", href: "/marketplace/education/coding-ksa", type: "course", price: "SAR 2,499" },
  { id: "ecourse-designing-life", name: "Designing Life", unit: "academy", tagline: "Life Design & Career Mastery", description: "Stanford-style life design methodology adapted for healthcare professionals — career pivoting, purpose mapping, and sustainable growth.", keywords: ["life design", "career", "healthcare professionals", "purpose", "growth", "stanford methodology"], categories: ["education", "course", "career", "wellness"], status: "Live", href: "/marketplace/education/designing-life", type: "course", price: "SAR 1,899" },
  { id: "ecourse-emergency-medicine", name: "Emergency Medicine Pro", unit: "academy", tagline: "Emergency Medicine Mastery", description: "Comprehensive emergency medicine course with interactive cases, algorithm trainers, and Arabic/English bilingual clinical scenarios.", keywords: ["emergency medicine", "clinical", "cases", "arabic", "bilingual", "algorithms", "triage"], categories: ["education", "course", "clinical", "emergency"], status: "Live", href: "/marketplace/education/emergency-medicine", type: "course", price: "SAR 3,499" },
  { id: "ecourse-lean-healthcare", name: "Lean Healthcare Operations", unit: "academy", tagline: "Lean Six Sigma for Healthcare", description: "Lean and Six Sigma methodology tailored for Saudi hospitals — value stream mapping, waste reduction, and quality improvement with local case studies.", keywords: ["lean", "six sigma", "healthcare operations", "quality improvement", "value stream", "saudi hospitals"], categories: ["education", "course", "operations", "quality"], status: "Live", href: "/marketplace/education/lean-healthcare", type: "course", price: "SAR 2,999" },
  { id: "ecourse-medical-manual", name: "دليل الطالب الطبي الحديث", unit: "academy", tagline: "Modern Medical Student Guide", description: "Premium Arabic interactive guide for medical students — study techniques, clinical rotations, exam prep, and career planning with Amiri/Tajawal typography.", keywords: ["medical student", "arabic", "study guide", "clinical rotations", "exams", "career", "amiri font"], categories: ["education", "course", "medical student", "arabic"], status: "Live", href: "/marketplace/education/medical-manual", type: "course", price: "SAR 1,499" },
  { id: "ecourse-nphies", name: "NPHIES Mastery", unit: "academy", tagline: "Saudi Health Information Exchange Certification", description: "Complete NPHIES technical certification — FHIR R4 transactions, claims submission, eligibility, prior auth, error resolution, and provider portal operations.", keywords: ["nphies", "fhir r4", "claims", "eligibility", "prior auth", "certification", "saudi", "health insurance"], categories: ["education", "course", "nphies", "certification", "integration"], status: "Live", href: "/marketplace/education/nphies", type: "course", price: "SAR 4,499" },
  { id: "ecourse-republic-of-cells", name: "Republic of Cells", unit: "academy", tagline: "Cell Biology & Systems Thinking", description: "Interactive cell biology course with systems thinking — organelles as city infrastructure, metabolic pathways as supply chains, DNA as code repositories.", keywords: ["cell biology", "systems thinking", "biology", "interactive", "metabolism", "dna", "education"], categories: ["education", "course", "biology", "science"], status: "Live", href: "/marketplace/education/republic-of-cells", type: "course", price: "SAR 1,799" },

  // ── BrainSAIT Ventures ──
  { id: "spark", name: "Spark", unit: "ventures", tagline: "AI-Native Innovation Engine", description: "Innovation management platform — crowdsource challenges, manage ideas, and accelerate health-tech solutions with AI-powered matching.", keywords: ["innovation", "ideas", "crowdsource", "challenges", "ideation", "spark"], categories: ["innovation", "ventures", "platform"], status: "Live", href: "/products/ventures/spark", type: "product" },
  { id: "incubator", name: "Incubator", unit: "ventures", tagline: "Health-Tech Incubation Program", description: "Full incubation for early-stage health-tech startups — AI tooling, GitHub automation, mentorship, and seed funding access.", keywords: ["incubator", "startup", "early-stage", "mentorship", "funding", "health-tech"], categories: ["ventures", "incubation", "startups"], status: "Live", href: "/products/ventures/incubator", type: "service" },
  { id: "accelerator", name: "Accelerator", unit: "ventures", tagline: "Growth-Stage Accelerator", description: "Intensive 12-week accelerator for growth-stage health-tech companies — market access, investor readiness, and enterprise pilots.", keywords: ["accelerator", "growth", "startup", "investor", "market access", "pilot"], categories: ["ventures", "acceleration", "startups"], status: "Live", href: "/products/ventures/accelerator", type: "service" },
  { id: "founder-os", name: "Founder OS", unit: "ventures", tagline: "Startup Operating System", description: "All-in-one toolkit for health-tech founders — cap table management, compliance tracking, investor updates, and milestone planning.", keywords: ["founder", "startup", "cap table", "compliance", "investor", "milestones", "toolkit"], categories: ["ventures", "tools", "founders"], status: "Beta", href: "/products/ventures/founder-os", type: "product" },
  { id: "startup-crm", name: "Startup CRM", unit: "ventures", tagline: "Health-Tech CRM", description: "Purpose-built CRM for health-tech startups — hospital outreach, procurement tracking, partnership management, and deal pipeline.", keywords: ["crm", "startup", "sales", "outreach", "hospital", "procurement", "deals"], categories: ["ventures", "crm", "sales"], status: "Beta", href: "/products/ventures/startup-crm", type: "product" },
  { id: "investor-portal", name: "Investor Portal", unit: "ventures", tagline: "Startup Investment Platform", description: "Curated investor access to vetted health-tech startups — deal flow, due diligence materials, and portfolio tracking.", keywords: ["investor", "investment", "deal flow", "due diligence", "portfolio", "startup"], categories: ["ventures", "investment", "finance"], status: "Live", href: "/products/ventures/investor-portal", type: "product" },
  { id: "mentor-portal", name: "Mentor Portal", unit: "ventures", tagline: "Expert Mentorship Network", description: "Connect with healthcare industry experts, clinical advisors, and seasoned entrepreneurs for 1-on-1 guidance.", keywords: ["mentor", "mentorship", "advisor", "expert", "guidance", "network"], categories: ["ventures", "mentorship", "network"], status: "Live", href: "/products/ventures/mentor-portal", type: "service" },
  { id: "demo-day", name: "Demo Day Platform", unit: "ventures", tagline: "Virtual & Hybrid Demo Days", description: "Platform for hosting demo days — pitch videos, live Q&A, investor matching, and follow-up tracking.", keywords: ["demo day", "pitch", "investor", "event", "presentation", "startup"], categories: ["ventures", "events", "investment"], status: "Live", href: "/products/ventures/demo-day", type: "product" },
  { id: "startup-marketplace", name: "Startup Marketplace", unit: "ventures", tagline: "Health-Tech Startup Directory", description: "Discover and connect with vetted health-tech startups — solutions for every healthcare challenge.", keywords: ["startup", "directory", "marketplace", "health-tech", "discover", "solutions"], categories: ["ventures", "marketplace", "network"], status: "Live", href: "/products/ventures/startup-marketplace", type: "product" },
];

export function getCatalog(): CatalogProduct[] {
  return CATALOG;
}

export function getCatalogByUnit(unit: string): CatalogProduct[] {
  return CATALOG.filter((p) => p.unit === unit);
}

export function getCatalogByCategory(category: string): CatalogProduct[] {
  return CATALOG.filter((p) => p.categories.includes(category));
}

export function getAllCategories(): string[] {
  const set = new Set<string>();
  CATALOG.forEach((p) => p.categories.forEach((c) => set.add(c)));
  return Array.from(set).sort();
}

export function getAllUnits(): string[] {
  return Array.from(new Set(CATALOG.map((p) => p.unit)));
}
