export type ProductCategory =
  | "course"
  | "template"
  | "book"
  | "document"
  | "consultation"
  | "subscription"
  | "framework"
  | "tool"
  | "certification";

export interface Product {
  id: string;
  name: string;
  description: string;
  category: ProductCategory;
  priceSAR: number;
  originalPriceSAR?: number;
  badge?: string;
  features: string[];
  digital: boolean;
  href?: string;
}

const COURSES: Product[] = [
  {
    id: "course-icd10",
    name: "ICD-10-CM/PCS Certification Program",
    description: "Comprehensive 12-week medical coding certification with AAPC-aligned curriculum. Includes mock exams, coding exercises, and instructor support.",
    category: "course",
    priceSAR: 8500,
    originalPriceSAR: 12000,
    badge: "Best Seller",
    features: ["12 weeks access", "AAPC-aligned", "Mock exams included", "Certificate of completion", "Instructor support"],
    digital: true,
    href: "/marketplace/education",
  },
  {
    id: "course-fhir",
    name: "FHIR R4 Fundamentals & Implementation",
    description: "8-week hands-on FHIR R4 course covering resources, APIs, terminology, and real-world implementation patterns.",
    category: "course",
    priceSAR: 6000,
    originalPriceSAR: 9000,
    badge: "Popular",
    features: ["8 weeks access", "Hands-on labs", "FHIR API sandbox", "Implementation guide", "Community access"],
    digital: true,
    href: "/marketplace/education",
  },
  {
    id: "course-ai-healthcare",
    name: "AI in Healthcare: Concept to Deployment",
    description: "Advanced 10-week program covering clinical AI, NLP, computer vision, MLOps, and Saudi regulatory compliance.",
    category: "course",
    priceSAR: 12000,
    originalPriceSAR: 18000,
    badge: "Expert",
    features: ["10 weeks access", "Clinical AI focus", "PDPL compliance module", "Capstone project", "Mentorship sessions"],
    digital: true,
    href: "/marketplace/education",
  },
  {
    id: "course-saudi-regs",
    name: "Saudi Healthcare Regulations & Compliance",
    description: "6-week essential course on PDPL, NPHIES, MOH regulations, and healthcare compliance in KSA.",
    category: "course",
    priceSAR: 4500,
    badge: "Essential",
    features: ["6 weeks access", "PDPL deep-dive", "NPHIES module", "Regulatory updates", "Compliance checklist"],
    digital: true,
    href: "/marketplace/education",
  },
  {
    id: "course-nphies",
    name: "NPHIES Integration Masterclass",
    description: "Hands-on masterclass for integrating with NPHIES claims, eligibility, and prior authorization APIs.",
    category: "course",
    priceSAR: 15000,
    originalPriceSAR: 22000,
    badge: "Premium",
    features: ["Full NPHIES API coverage", "Sandbox environment", "Code templates", "Live Q&A sessions", "Integration certification"],
    digital: true,
    href: "/marketplace/education",
  },
];

const TEMPLATES: Product[] = [
  {
    id: "template-medical-coding",
    name: "Medical Coding Template Bundle",
    description: "Professional ICD-10, CPT, and HCPCS coding templates for emergency, inpatient, surgical, and outpatient settings.",
    category: "template",
    priceSAR: 2500,
    badge: "Most Popular",
    features: ["50+ coding templates", "ICD-10-AM compliant", "CPT modifiers included", "Editable formats", "Monthly updates"],
    digital: true,
    href: "/marketplace/education",
  },
  {
    id: "template-fhir-impl",
    name: "FHIR Implementation Toolkit",
    description: "Complete FHIR R4 implementation templates including StructureDefinition, ValueSet, and OperationDefinition patterns.",
    category: "template",
    priceSAR: 3500,
    originalPriceSAR: 5000,
    features: ["FHIR R4 templates", "SD/VS/OD patterns", "Example resources", "Validation scripts", "Best practices guide"],
    digital: true,
  },
  {
    id: "template-nphies-forms",
    name: "NPHIES Claim Forms & Workflows",
    description: "Ready-to-use NPHIES claim submission templates, prior authorization forms, and eligibility check workflows.",
    category: "template",
    priceSAR: 3000,
    features: ["Claim form templates", "Prior auth workflows", "Eligibility check scripts", "Arabic/English bilingual", "Integration guide"],
    digital: true,
  },
  {
    id: "template-compliance",
    name: "PDPL Compliance Documentation Kit",
    description: "Complete PDPL compliance documentation templates including DPIAs, consent forms, data mapping, and policies.",
    category: "template",
    priceSAR: 5000,
    originalPriceSAR: 7000,
    badge: "Essential",
    features: ["DPIA templates", "Consent form templates", "Data mapping worksheets", "Policy documents", "Compliance checklist"],
    digital: true,
  },
  {
    id: "template-hipaa",
    name: "HIPAA Alignment Documentation Set",
    description: "Documentation templates for aligning Saudi healthcare operations with HIPAA privacy, security, and breach notification rules.",
    category: "template",
    priceSAR: 4000,
    features: ["Privacy rule docs", "Security rule templates", "Breach notification forms", "RA templates", "BA agreement templates"],
    digital: true,
  },
];

const BOOKS: Product[] = [
  {
    id: "book-fhir-handbook",
    name: "FHIR R4 Handbook for Saudi Healthcare",
    description: "The definitive guide to implementing FHIR R4 in the Saudi healthcare ecosystem. Covers NPHIES, PDPL, and national standards.",
    category: "book",
    priceSAR: 350,
    badge: "New",
    features: ["300+ pages", "Saudi-specific content", "NPHIES integration chapter", "PDF + ePub formats", "Regular updates"],
    digital: true,
  },
  {
    id: "book-ai-clinical",
    name: "AI in Clinical Practice: A Saudi Perspective",
    description: "Practical guide for clinicians and health IT leaders on adopting AI in Saudi healthcare settings.",
    category: "book",
    priceSAR: 280,
    features: ["250+ pages", "Case studies from KSA", "Implementation frameworks", "Arabic glossary", "Digital edition"],
    digital: true,
  },
  {
    id: "book-medical-coding",
    name: "Medical Coding in the GCC: Complete Guide",
    description: "Comprehensive reference for medical coding in Gulf Cooperation Council countries with ICD-10-AM focus.",
    category: "book",
    priceSAR: 420,
    originalPriceSAR: 550,
    badge: "Reference",
    features: ["400+ pages", "ICD-10-AM complete", "CPT/HCPCS included", "GCC-specific guidelines", "Practice exercises"],
    digital: true,
  },
  {
    id: "book-digital-health",
    name: "Digital Health Transformation: Saudi Vision 2030",
    description: "Strategic guide for healthcare leaders navigating digital transformation aligned with Saudi Vision 2030.",
    category: "book",
    priceSAR: 320,
    features: ["280+ pages", "Vision 2030 roadmap", "Case studies", "Implementation playbook", "Executive summary"],
    digital: true,
  },
  {
    id: "book-nphies-api",
    name: "NPHIES API Integration: Developer's Guide",
    description: "Technical deep-dive into NPHIES APIs with code examples, testing strategies, and deployment patterns.",
    category: "book",
    priceSAR: 450,
    badge: "Technical",
    features: ["350+ pages", "Code examples in JS/Python", "API reference", "Testing guide", "Sandbox exercises"],
    digital: true,
  },
];

const DOCUMENTS: Product[] = [
  {
    id: "doc-saudi-fhir",
    name: "Saudi FHIR Implementation Guidelines",
    description: "Official implementation guidelines for FHIR R4 in Saudi Arabia covering all national profiles and extensions.",
    category: "document",
    priceSAR: 1500,
    badge: "Professional",
    features: ["Full guidelines document", "Profile definitions", "Extension catalog", "Example instances", "Validation rules"],
    digital: true,
  },
  {
    id: "doc-nphies-spec",
    name: "NPHIES Technical Specification Bundle",
    description: "Complete NPHIES API specifications, XSD schemas, and integration patterns for claims and eligibility.",
    category: "document",
    priceSAR: 2000,
    originalPriceSAR: 3000,
    features: ["API specifications", "XSD schemas", "Sample requests/responses", "Error handling guide", "Version history"],
    digital: true,
  },
  {
    id: "doc-pdpl-guide",
    name: "PDPL Compliance Implementation Guide",
    description: "Step-by-step guide for implementing PDPL compliance in healthcare organizations of all sizes.",
    category: "document",
    priceSAR: 1800,
    features: ["Implementation steps", "Risk assessment framework", "Rights management", "Breach response plan", "Audit checklists"],
    digital: true,
  },
  {
    id: "doc-medical-coding",
    name: "Medical Coding Standards & Audit Guide",
    description: "Comprehensive guide to medical coding standards, audit methodologies, and quality improvement for Saudi healthcare.",
    category: "document",
    priceSAR: 1200,
    features: ["Coding standards", "Audit methodology", "Quality metrics", "Training material", "Sample reports"],
    digital: true,
  },
];

const CONSULTATIONS: Product[] = [
  {
    id: "consult-fhir",
    name: "FHIR Implementation Consultation (1 Hour)",
    description: "One-on-one session with a senior FHIR architect. Covers architecture review, implementation planning, and troubleshooting.",
    category: "consultation",
    priceSAR: 1500,
    features: ["60-minute session", "Architecture review", "Implementation plan", "Follow-up summary", "Priority support"],
    digital: true,
    href: "/marketplace/experts",
  },
  {
    id: "consult-nphies",
    name: "NPHIES Integration Consultation (1 Hour)",
    description: "Expert guidance on NPHIES integration including API strategy, testing approach, and go-live planning.",
    category: "consultation",
    priceSAR: 2000,
    features: ["60-minute session", "Integration roadmap", "API strategy", "Testing approach", "Go-live checklist"],
    digital: true,
    href: "/marketplace/experts",
  },
  {
    id: "consult-coding",
    name: "Medical Coding Audit & Optimization (2 Hours)",
    description: "Comprehensive coding audit with recommendations for revenue cycle optimization and compliance improvement.",
    category: "consultation",
    priceSAR: 2500,
    features: ["2-hour deep-dive", "Coding audit", "Revenue cycle review", "Action plan", "Follow-up report"],
    digital: true,
    href: "/marketplace/experts",
  },
];

const SUBSCRIPTIONS: Product[] = [
  {
    id: "sub-api",
    name: "NPHIES Connector API - Monthly",
    description: "Full NPHIES integration API access: eligibility, prior auth, claims submission, and remittance.",
    category: "subscription",
    priceSAR: 5000,
    badge: "Popular",
    features: ["Unlimited API calls", "Real-time eligibility", "Claims submission", "Prior authorization", "Email support"],
    digital: true,
    href: "/marketplace/api",
  },
  {
    id: "sub-api-pro",
    name: "NPHIES Connector API - Annual",
    description: "Annual NPHIES API subscription with priority support, SLA guarantee, and advanced analytics.",
    category: "subscription",
    priceSAR: 50000,
    originalPriceSAR: 60000,
    badge: "Best Value",
    features: ["All monthly features", "Priority support", "99.99% SLA", "Advanced analytics", "Dedicated account manager"],
    digital: true,
    href: "/marketplace/api",
  },
];

// ─── Saudi Healthcare Documents & Information Governance Framework ───

const GOVERNANCE_FRAMEWORKS: Product[] = [
  {
    id: "framework-complete",
    name: "Saudi Healthcare Information Governance Framework — Complete Bundle",
    description: "The definitive, enterprise-grade information governance framework for Saudi healthcare organisations. Covers PDPL, NPHIES, MOH, CBAHI, and international standards (ISO 27001, HIPAA) in one integrated system. Includes 200+ editable policy templates, implementation guides, audit checklists, training materials, and a customisable governance maturity model.",
    category: "framework",
    priceSAR: 45000,
    originalPriceSAR: 65000,
    badge: "Enterprise",
    features: [
      "200+ editable policy & procedure templates",
      "PDPL compliance toolkit with DPIA templates",
      "NPHIES information governance module",
      "Records retention schedule (MOH-compliant)",
      "Data classification framework & taxonomy",
      "Information asset register template",
      "Access control & identity governance playbook",
      "Consent management framework & forms (Arabic/English)",
      "Breach response & incident management plan",
      "Vendor risk assessment framework",
      "Governance maturity model & self-assessment tool",
      "Board-level governance dashboard templates",
      "Training & awareness program materials",
      "Audit checklist set (internal & external)",
      "Business continuity & disaster recovery framework",
      "12 months of updates & priority support",
    ],
    digital: true,
  },
  {
    id: "framework-pdpl",
    name: "PDPL Compliance Toolkit — Saudi Healthcare Edition",
    description: "A comprehensive PDPL compliance package purpose-built for healthcare providers, insurers, and health-tech companies in Saudi Arabia. Maps every PDPL article to actionable policies, procedures, and operational controls with bilingual (Arabic/English) templates.",
    category: "framework",
    priceSAR: 18000,
    originalPriceSAR: 25000,
    badge: "Popular",
    features: [
      "PDPL article-by-article compliance mapping",
      "Data Protection Impact Assessment (DPIA) templates",
      "Privacy notice & consent form templates (Ar/En)",
      "Data subject rights request workflow",
      "Data processing register template",
      "Data breach notification procedure",
      "Privacy governance policy suite (15+ policies)",
      "Employee privacy training materials",
      "Cross-border data transfer mechanism guidance",
      "Regulatory reporting templates",
      "Compliance gap analysis tool",
      "Implementation roadmap & project plan",
    ],
    digital: true,
  },
  {
    id: "framework-nphies-data",
    name: "NPHIES Data Governance & Exchange Framework",
    description: "Specialised information governance framework for organisations integrating with NPHIES. Covers claims data governance, eligibility verification protocols, prior authorization data handling, and cross-system data quality standards.",
    category: "framework",
    priceSAR: 15000,
    originalPriceSAR: 22000,
    badge: "Specialised",
    features: [
      "NPHIES data governance policy suite",
      "Claims data quality framework",
      "Eligibility data handling protocols",
      "Prior authorization data governance",
      "Remittance advice data management",
      "Data exchange agreements template",
      "Interoperability governance framework",
      "FHIR data governance addendum",
      "Data stewardship & ownership matrix",
      "Operational data quality dashboards",
      "NPHIES-specific audit checklists",
      "Integration testing governance guide",
    ],
    digital: true,
  },
  {
    id: "framework-records",
    name: "Healthcare Records & Document Management Framework",
    description: "End-to-end records and document management framework compliant with MOH, CBAHI, and international standards. Covers the complete records lifecycle from creation through retention to secure disposal.",
    category: "framework",
    priceSAR: 12000,
    originalPriceSAR: 18000,
    badge: "Essential",
    features: [
      "Records management policy & procedure suite",
      "MOH-compliant retention schedule (all document types)",
      "Electronic document management system (EDMS) spec",
      "Document classification & indexing taxonomy",
      "Version control & approval workflows framework",
      "Physical records management standards",
      "Digital preservation & archiving policies",
      "Records disposal & destruction procedures",
      "Business classification scheme",
      "Document imaging & digitisation standards",
      "Access & security classification framework",
      "Records management training materials",
    ],
    digital: true,
  },
  {
    id: "framework-access",
    name: "Identity & Access Governance for Healthcare",
    description: "Comprehensive IAM governance framework tailored for healthcare organisations. Addresses role-based access control (RBAC), clinical system access, privileged access management, and Saudi national e-authentication standards.",
    category: "framework",
    priceSAR: 10000,
    originalPriceSAR: 15000,
    features: [
      "Identity governance policy suite",
      "RBAC role matrix for healthcare (150+ roles)",
      "Clinical system access control templates",
      "Privileged access management framework",
      "Authentication & MFA policy templates",
      "Access certification & recertification workflow",
      "User provisioning & de-provisioning procedures",
      "Identity federation & SSO governance",
      "Access audit log standards",
      "National e-authentication compliance mapping",
      "IAM maturity assessment tool",
      "Identity governance training program",
    ],
    digital: true,
  },
  {
    id: "framework-risk",
    name: "Healthcare Information Risk Management Framework",
    description: "Enterprise risk management framework aligned with ISO 31000, NIST CSF, and Saudi NCA standards. Integrated with healthcare operational risk, patient safety, and information security domains.",
    category: "framework",
    priceSAR: 14000,
    originalPriceSAR: 20000,
    features: [
      "Enterprise risk management policy framework",
      "Information risk assessment methodology",
      "Risk register template with healthcare scenarios",
      "Third-party/vendor risk management program",
      "Business impact analysis (BIA) templates",
      "Business continuity & disaster recovery plans",
      "Incident response & escalation procedures",
      "Risk appetite & tolerance statements",
      "Control testing & assurance framework",
      "Risk reporting & board dashboard templates",
      "NCA compliance mapping toolkit",
      "Risk management training & awareness pack",
    ],
    digital: true,
  },
  {
    id: "framework-clinical-safety",
    name: "Clinical Safety & Health IT Governance Framework",
    description: "Specialised governance framework for clinical safety of health IT systems. Covers DCB 0129 (clinical risk management), patient safety incident management, and AI governance in clinical settings.",
    category: "framework",
    priceSAR: 16000,
    originalPriceSAR: 24000,
    badge: "Premium",
    features: [
      "Clinical safety management policy suite",
      "DCB 0129/0160 compliance toolkit",
      "Clinical risk assessment templates",
      "Patient safety incident management framework",
      "Health IT change control governance",
      "AI governance & ethics framework for healthcare",
      "Clinical decision support governance",
      "Telehealth governance & safety standards",
      "Mobile health application governance",
      "Clinical safety case report template",
      "Safety validation & verification checklists",
      "Clinical governance committee terms of reference",
    ],
    digital: true,
  },
  {
    id: "framework-training",
    name: "Governance Awareness & Training Program Bundle",
    description: "Ready-to-deploy training and awareness program covering information governance, data protection, and cybersecurity for all healthcare staff levels. Includes presentations, handouts, e-learning modules, and awareness campaign materials.",
    category: "framework",
    priceSAR: 8000,
    originalPriceSAR: 12000,
    badge: "Best Value",
    features: [
      "10 instructor-led training module decks",
      "Staff awareness e-learning package (SCORM)",
      "Information governance induction materials",
      "Data protection awareness campaign kit",
      "Cybersecurity awareness monthly materials",
      "Role-specific training matrices (clinical/non-clinical)",
      "Training records & competency assessment templates",
      "Awareness posters & digital signage assets",
      "Newsletter templates for ongoing engagement",
      "Training effectiveness evaluation tools",
      "Board & senior leadership briefing packs",
      "Annual refresher program materials",
    ],
    digital: true,
  },
];

const GOVERNANCE_CONSULTATIONS: Product[] = [
  {
    id: "consult-governance-audit",
    name: "Information Governance Health Check & Gap Analysis",
    description: "Comprehensive 1-week engagement to assess your organisation's current information governance maturity against Saudi regulatory requirements. Delivers a detailed report with prioritised remediation roadmap.",
    category: "consultation",
    priceSAR: 15000,
    badge: "Audit",
    features: [
      "Remote/on-site assessment (5 days)",
      "Governance maturity evaluation",
      "Regulatory gap analysis (PDPL, NPHIES, MOH)",
      "Policy & procedure review",
      "Detailed findings report",
      "Prioritised remediation roadmap",
      "Executive summary presentation",
      "12-month action plan",
    ],
    digital: true,
  },
  {
    id: "consult-governance-impl",
    name: "Governance Framework Implementation Support (Monthly)",
    description: "Ongoing expert support to implement your information governance framework. Includes policy drafting, stakeholder engagement, training delivery, and assurance activities.",
    category: "consultation",
    priceSAR: 25000,
    badge: "Implementation",
    features: [
      "Dedicated governance advisor (20 hrs/month)",
      "Policy & procedure drafting support",
      "Stakeholder workshop facilitation",
      "Implementation project management",
      "Training delivery (up to 4 sessions/month)",
      "Quarterly progress reporting",
      "Regulatory update monitoring",
      "Email & phone support (business hours)",
    ],
    digital: true,
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...COURSES,
  ...TEMPLATES,
  ...BOOKS,
  ...DOCUMENTS,
  ...GOVERNANCE_FRAMEWORKS,
  ...CONSULTATIONS,
  ...GOVERNANCE_CONSULTATIONS,
  ...SUBSCRIPTIONS,
];

export const PRODUCTS_BY_CATEGORY: Record<ProductCategory, Product[]> = {
  course: COURSES,
  template: TEMPLATES,
  book: BOOKS,
  document: DOCUMENTS,
  consultation: [...CONSULTATIONS, ...GOVERNANCE_CONSULTATIONS],
  subscription: SUBSCRIPTIONS,
  framework: GOVERNANCE_FRAMEWORKS,
  tool: [],
  certification: [],
};

export function getProductById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function formatSAR(amount: number): string {
  return `SAR ${amount.toLocaleString("en-SA")}`;
}

export const SADAD_INFO = {
  billerName: "stc pay",
  billerCode: "207",
  sadadNumber: "72255534330",
  currency: "SAR",
  minDeposit: 5000,
};
